### ISSUE TITLE
Example usage commands seem unresponsive

### ISSUE THREAD

**Issue by reedv** [imbroglioj/xml-to-es#2]
OS: linux mint 18.2
node version: v7.10.1
npm version: 4.2.0

I may be understanding the documentation wrong, but using the xml to json conversion example
 `node examples/convert.js FILES_OR_DIRECTORY --config CONFIG_FILE [--level LOGLEVEL]` 
to do 
`node examples/convert.js $HOME/Documents/data_temp/sample_1.xml --config examples/json-config.js --level WARN` 
in the xml-to-es directory does not seem to generate any output. Should I be seeing json somewhere?

Testing with `npm test` shows all tests passing,  so I am not sure what is happening here.

Thanks :)

**Comment by imbroglioj** [comment]
The examples work on the data in the test/data/ directory (sgm and html file type endings). To run on an xml (not sgm) file:
1. sed 's/sgm/xml/g' examples/lewis-input-config.js >xml-input-config.js 
2. sed 's/lewis/xml/g' >examples/json-config.js >json-config.js
(Note the new edited config files should be in the same directory.)
3. rerun using your edited version of json-config.js as the --config arg
The output will be in the json/ subdirectory of your working directory.

By the way, in my new projects I have been using fast-xml2js (github.com/codyrigney92/fast-xml2js). It is convenient to use and very fast. (The ElasticSearch indexing part of xml-to-js can be easily abstracted into a web service.)

**Comment by reedv** [comment]
Thanks for the clarification
